#!/usr/bin/env python3
"""
generate_config.py — Generate Hermes config files on Railway startup.
Reads settings from environment variables and writes config.yaml,
.env, and hindsight/config.json to /hermes-data/.
"""
import json
import os
import sys
from pathlib import Path

DATA_DIR = Path("/hermes-data")
HERMES_HOME = Path("/root/.hermes")


def write_config_yaml():
    """Generate config.yaml"""
    template = """# Hermes Agent Configuration — Auto-generated by generate_config.py

model:
  default: '{model}'
  provider: openrouter
  base_url: https://openrouter.ai/api/v1
  api_key: ${{OPENROUTER_API_KEY}}

agent:
  max_turns: 150

terminal:
  backend: local
  timeout: 180

display:
  personality: '{personality}'
  show_reasoning: false
  show_cost: true

compression:
  enabled: true
  threshold: 0.50
  target_ratio: 0.20

memory:
  memory_enabled: true
  provider: hindsight
  auto_retain: true
  retain_every_n_turns: 1
  auto_recall: true

checkpoints:
  enabled: true
  max_snapshots: 50

stt:
  enabled: false

tts:
  provider: edge
"""

    ctx = {
        "model": os.environ.get("HERMES_MODEL", "@preset/hermes"),
        "personality": os.environ.get("HERMES_PERSONALITY", "kawaii"),
    }

    out = DATA_DIR / "config.yaml"
    out.write_text(template.format(**ctx))
    print(f"  config.yaml written ({ctx['model']})")


def write_env():
    """Generate .env from Railway environment variables"""
    secrets = [
        ("OPENROUTER_API_KEY", "OPENROUTER_API_KEY"),
        ("API_SERVER_KEY", "API_SERVER_KEY"),
        ("DISCORD_BOT_TOKEN", "DISCORD_BOT_TOKEN"),
        ("TELEGRAM_BOT_TOKEN", "TELEGRAM_BOT_TOKEN"),
        ("GH_TOKEN", "GH_TOKEN"),
    ]

    lines = []
    for railway_name, hermes_name in secrets:
        val = os.environ.get(railway_name, "")
        if val:
            lines.append(f"{hermes_name}={val}")

    # API server enabled for dashboard
    lines.append("API_SERVER_ENABLED=true")
    lines.append("API_SERVER_PORT=8642")

    # Hindsight: local_embedded mode with local PostgreSQL
    lines.append("HINDSIGHT_MODE=local_embedded")
    lines.append("HINDSIGHT_URL=http://localhost:8888")
    lines.append("HINDSIGHT_BANK_ID={}".format(
        os.environ.get("HINDSIGHT_BANK_ID", "hermes-railway")
    ))

    # DB connection for embedded Hindsight
    pg_host = os.environ.get("PGHOST", "localhost")
    pg_port = os.environ.get("PGPORT", "5432")
    lines.append(f"HINDSIGHT_DB_URL=postgresql://postgres@{pg_host}:{pg_port}/hindsight")

    out = DATA_DIR / ".env"
    out.write_text("\n".join(lines) + "\n")
    print(f"  .env written ({len(lines)} vars)")


def write_hindsight_config():
    """Generate hindsight/config.json"""
    hindsight_url = os.environ.get("HINDSIGHT_URL", "http://localhost:8888")
    bank_id = os.environ.get("HINDSIGHT_BANK_ID", "hermes-railway")

    cfg = {
        "mode": "local_embedded",
        "api_url": hindsight_url,
        "bank_id": bank_id,
        "recall_budget": "mid",
        "auto_retain": True,
        "retain_every_n_turns": 1,
        "auto_recall": True,
        "retain_async": True,
    }

    hdir = DATA_DIR / "hindsight"
    hdir.mkdir(parents=True, exist_ok=True)
    out = hdir / "config.json"
    out.write_text(json.dumps(cfg, indent=2) + "\n")
    print(f"  hindsight/config.json written (bank={bank_id})")


def symlink_to_hermes_home():
    """Symlink generated configs into ~/.hermes/"""
    HERMES_HOME.mkdir(parents=True, exist_ok=True)

    for name in ["config.yaml", ".env", "hindsight"]:
        src = DATA_DIR / name
        dst = HERMES_HOME / name
        if src.exists():
            if dst.is_symlink() or dst.exists():
                dst.unlink()
            dst.symlink_to(src)
            print(f"  ~/.hermes/{name} -> {src}")


def main():
    print("[generate_config] Writing Hermes configuration...")
    DATA_DIR.mkdir(parents=True, exist_ok=True)

    try:
        write_config_yaml()
        write_env()
        write_hindsight_config()
        symlink_to_hermes_home()
        print("[generate_config] ✓ Done.")
    except Exception as e:
        print(f"[generate_config] ✗ ERROR: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
